server:
  port: 8080

#frontDomain: "http://localhost:3000"

#deploy
frontDomain: "http://13.125.173.232"

#배포할때 유의
dbDomain : "mysql://13.125.244.70:3306"
dbUser : "shop"
dbPasswd : "1234"

spring:
  datasource:
    url: jdbc:${dbDomain}/reactdemo?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: ${dbUser}
    password: ${dbPasswd}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  issuer: reactdemo #토큰발급자
  secret-key: jwtSecretKey




